name: CI checks

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  file-changes:
    name: Check location of file changes
    runs-on: ubuntu-latest
    outputs:
      P1: ${{ steps.filter.outputs.P1 }}
      P2: ${{ steps.filter.outputs.P2 }}
    steps:
      - uses: actions/checkout@v4
      - uses: dorny/paths-filter@v2
        id: filter
        with:
          filters: |
            P1:
              - 'P1/**'
            P2:
              - 'P2/**'

      
  P1-CI-checks:
    needs: file-changes
    if: ${{ needs.file-changes.outputs.P1 == 'true' }}
    name: P1 CI checks
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python 3.12.1
        uses: actions/setup-python@v4
        with:
          python-version: "3.12.1"

      - name: Install Poetry
        run: |
          curl -sSL https://install.python-poetry.org | python3 -

      - name: Install dependencies
        run: |
          poetry install --no-interaction --no-root

      - name: Run pytest
        run: |
          export PYTHONPATH=$PYTHONPATH:$(pwd)
          poetry run pytest

      - name: Run isort
        run: |
          poetry run isort --check-only --diff .

      - name: Run black
        run: |
          poetry run black --check --diff .

      - name: Run Mypy
        run: |
          poetry run mypy .

      - name: Run Pylint
        run: |
          poetry run pylint **/*.py
